mergesort: mergesort.c
	gcc -O2 -o mergesort mergesort.c mergesort_wrap.c -I /home/josiah/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/ruby -I /home/josiah/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/x86_64-linux/ruby


